version: "3.7"
services:
  db:
    image: "mysql:5.7"
    environment:
      MYSQL_ROOT_PASSWORD: offer123
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: offer123
    ports:
      - "3307:3306"
  web:
    depends_on:
      - "db"
    build: .
    ports:
      - "3000:3000"
    environment:
      DB_USERNAME: root
      DB_PASSWORD: offer123
      DB_DATABASE: offers
      DB_PORT: 3306
      DB_HOST: db
      RAILS_ENV: development
      RAILS_MAX_THREADS: 5
    volumes:
      - ".:/app"
      - "./config/docker/database.yml:/app/config/database.yml"

volumes:
  db:
